general:

  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:
    sequences:
      priority_level_4: [ sq_auto_auto_drivetrain_straightline, sq_climber_extend ]

    parallels:

    ss_drivetrain:
      priority_level_2: [ st_drivetrain_zero ]
      priority_level_1: [ st_drivetrain_straightline ]
      default: [ st_drivetrain_swerve ]

    ss_climber:
      priority_level_1: [ st_climber_extend, st_climber_retract, st_climber_retract_no_ratchet, wt_climber_retract_no_ratchet,
                          st_climber_no_ratchet, wt_climber_no_ratchet ]
      default: [ st_climber_stop ]

  subsystems: [ ss_drivetrain, ss_climber ]

  input_booleans: [ ipb_driver_back, ipb_driver_start, ipb_driver_left_trigger, ipb_driver_left_bumper, ipb_driver_a, ipb_driver_x, ipb_driver_y, ipb_driver_b, ipb_driver_right_bumper, ipb_driver_right_trigger, ipb_driver_dpad_up, ipb_driver_dpad_down,
                    ipb_operator_back, ipb_operator_start ]

  input_numerics: [ ipn_driver_left_y, ipn_driver_left_x, ipn_driver_right_y, ipn_driver_right_x, ipn_operator_left_y ]

  input_vectors: [ ipv_navx, ipv_pigeon,
                   ipv_drivetrain_front_right_angle, ipv_drivetrain_front_left_angle, ipv_drivetrain_back_left_angle, ipv_drivetrain_back_right_angle,
                   ipv_swerve_odometry]

  output_numerics: [ opn_drivetrain_front_right_speed, opn_drivetrain_front_left_speed, opn_drivetrain_back_left_speed, opn_drivetrain_back_right_speed,
                     opn_drivetrain_front_right_angle, opn_drivetrain_front_left_angle, opn_drivetrain_back_left_angle, opn_drivetrain_back_right_angle,
                     opn_climber_winch, opn_climber_ratchet ]

  output_booleans: [ ]

global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain_swerve:
  module_positions: [ [ 11.5 , -11.5 ], [ 11.5, 11.5 ], [ -11.5, 11.5 ], [ -11.5, -11.5 ] ]
  input_angle_names: [ ipv_drivetrain_front_right_angle, ipv_drivetrain_front_left_angle, ipv_drivetrain_back_left_angle, ipv_drivetrain_back_right_angle ]
  input_position_names: [ ipn_drivetrain_front_right_speed_position, ipn_drivetrain_front_left_speed_position, ipn_drivetrain_back_left_speed_position, ipn_drivetrain_back_right_speed_position]
  output_angle_names: [ opn_drivetrain_front_right_angle, opn_drivetrain_front_left_angle, opn_drivetrain_back_left_angle, opn_drivetrain_back_right_angle ]
  output_speed_names: [ opn_drivetrain_front_right_speed, opn_drivetrain_front_left_speed, opn_drivetrain_back_left_speed, opn_drivetrain_back_right_speed ]
  navx: ipv_navx
  pigeon: ipv_pigeon
  limelight: none
  odometry: ipv_swerve_odometry
  heading_controller: pr_swerve_heading
  swerve_x: ipn_driver_left_x
  swerve_y: ipn_driver_left_y
  swerve_rotate: ipn_driver_right_x
  swerve_field_oriented_button: ipb_driver_start
  angle_zero_button: ipb_driver_back
  max_module_velocity: 240.0
  corner_mode_max_velocity: 80
  normal_mode_max_velocity: 120
  slow_mode_max_velocity: 20
  fast_mode_button: ipb_driver_a
  corner_mode_button: ipb_driver_right_trigger
  slow_mode_button: ipb_driver_left_trigger
  velocity_increment_button: ipb_driver_dpad_up
  velocity_decrement_button: ipb_driver_dpad_down
  velocity_increment: 10

global_climber:
  climber_joystick: ipn_operator_left_y

log:
#  ips_selected_auto: true

global_webdashboard:

  auto_selector:
    origins: [ auto ]
    destinations: [ drivetrain ]
    actions: [ straightline ]

  match_values:

    ips_mode:
      display_name: Mode
      type: string

    ipb_field_oriented:
      display_name: Swerve Field Oriented
      type: boolean

    ipb_endgame_enabled:
      display_name: Climb Enabled
      type: boolean

