general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:
      priority_level_2: []
      priority_level_1: [sq_climber_extend, sq_hopper_prime,
                         sq_auto_anywhere_0ball_forward, sq_auto_right_8ball_trench, sq_auto_goal_8ball_generator, sq_auto_anywhere_3ball_none, sq_auto_left_5ball_steal]
    parallels:
      priority_level_3: [pl_dejam]
      priority_level_2: [pl_shoot]
      priority_level_1: [pl_stop_all, pl_collect_floor, pl_prime_to_shoot, wt_shoot_all, wt_shoot_all_final,
                         pl_prime_drive_right_line_to_trenchfront, pl_collect_drive_right_trenchfront_to_trenchback, pl_collect_drive_right_trenchback_to_trenchmid, pl_prime_drive_right_trenchmid_to_trenchfront, pl_prime_drive_anywhere_line_to_behindline,
                         pl_prime_drive_goal_line_to_goalback, pl_collect_drive_goalback_to_generator, pl_collect_drive_generator_to_rightgenerator, pl_prime_drive_rightgenerator_to_goalback, pl_collect_drive_left_line_to_trenchback, pl_collect_drive_left_trenchback_to_midfield, pl_prime_drive_left_midfield_to_goal]
    ss_drivetrain:
      priority_level_3: [st_drivetrain_zero]
      priority_level_2: []
      priority_level_1: [st_drivetrain_velocity, st_drivetrain_percent,
                         st_drive_anywhere_0ball_forward, st_drive_right_line_to_trenchfront, st_drive_right_trenchfront_to_trenchback, st_drive_right_trenchback_to_trenchmid, st_drive_right_trenchmid_to_trenchfront, st_drive_anywhere_line_to_behindline,
                         st_drive_goal_line_to_goalback, st_drive_goalback_to_generator, st_drive_generator_to_rightgenerator, st_drive_rightgenerator_to_goalback, st_drive_left_line_to_trenchback, st_drive_left_trenchback_to_midfield, st_drive_left_midfield_to_goal]
      default: [st_drivetrain_percent]
    ss_collector:
      priority_level_3: [st_collector_zero]
      priority_level_2: [st_collector_eject]
      priority_level_1: [st_collector_manual, st_collector_extend, st_collector_retract, st_collector_floor_intake]
      default: [st_collector_stop]
    ss_hopper:
      priority_level_3: [st_hopper_zero]
      priority_level_2: [st_hopper_reverse]
      priority_level_1: [st_hopper_manual, st_hopper_home, st_hopper_load, st_hopper_shoot]
      default: [st_hopper_stop]
    ss_elevator:
      priority_level_3: [st_elevator_zero]
      priority_level_2: [ ]
      priority_level_1: [st_elevator_manual, st_elevator_shoot]
      default: [st_elevator_stop]
    ss_turret:
      priority_level_3: [st_turret_zero]
      priority_level_2: [st_turret_dejam]
      priority_level_1: [st_turret_manual, st_turret_aim_from_trench, st_turret_align, st_turret_endgame]
      default: [st_turret_center]
    ss_flywheel:
      priority_level_3: [st_flywheel_zero]
      priority_level_2: [st_flywheel_reverse]
      priority_level_1: [st_flywheel_manual, st_flywheel_prime, st_flywheel_shoot]
      default: [st_flywheel_stop]
    ss_climber:
      priority_level_3: [st_climber_zero]
      priority_level_2: []
      priority_level_1: [st_climber_extend, st_climber_retract, st_climber_no_ratchet, st_climber_retract_no_ratchet,
                         wt_climber_no_ratchet, wt_climber_retract_no_ratchet]
      default: [st_climber_stop]

  subsystems: [ss_drivetrain, ss_collector, ss_hopper, ss_elevator, ss_turret, ss_flywheel, ss_climber]

  input_booleans: [
    ipb_driver_a, ipb_driver_b, ipb_driver_y, ipb_driver_x, ipb_driver_left_bumper, ipb_driver_right_bumper, ipb_driver_left_trigger, ipb_driver_right_trigger, ipb_driver_dpad_up, ipb_driver_dpad_down, ipb_driver_dpad_left, ipb_driver_dpad_right, ipb_driver_back, ipb_driver_start, ipb_driver_left_stick_button, ipb_driver_right_stick_button,
    ipb_operator_a, ipb_operator_b, ipb_operator_y, ipb_operator_x, ipb_operator_left_bumper, ipb_operator_right_bumper, ipb_operator_left_trigger, ipb_operator_right_trigger, ipb_operator_dpad_up, ipb_operator_dpad_down, ipb_operator_dpad_left, ipb_operator_dpad_right, ipb_operator_back, ipb_operator_start, ipb_operator_left_stick_button, ipb_operator_right_stick_button,
    ipb_hopper_home_switch, ipb_elevator_beam_sensor
  ]

  input_numerics: [
    ipn_driver_left_y, ipn_driver_left_x, ipn_driver_right_y, ipn_driver_right_x,
    ipn_operator_left_y, ipn_operator_left_x, ipn_operator_right_y, ipn_operator_right_x
  ]

  input_vectors: [ipv_odometry, ipv_navx, ipv_limelight_turret]

  output_numerics: [opn_drivetrain_left, opn_drivetrain_right, opn_collector_rollers, opn_hopper, opn_elevator, opn_flywheel, opn_turret, opn_climber_winch, opn_climb_roller]

  output_booleans: [opb_drivetrain_gear_shifter, opb_collector_extend, opb_climber_ratchet, opb_elevator_extend ]


global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain:
  x: ipn_driver_right_x
  y: ipn_driver_left_y
  gear_shift_button: ipb_driver_left_trigger
  velocity_mode_button: ipb_driver_right_bumper
  limelight_align_mode_button: ipb_driver_left_bumper
  pure_pursuit_track_width: 30.0

global_collector:
  deploy_button: ipb_operator_left_trigger
  roller_speed_button: ipb_operator_left_bumper

global_hopper:
  increment_speed_up_button: ipb_operator_b
  increment_speed_down_button: ipb_operator_x
  enabled_button: ipb_operator_right_bumper
  initial_speed: 0.0
  increment_speed: 0.1
  start_moving_timer_length: 750
  dejam_timer_length: 3000
  spin_up_timer_length: 500
  dejam_speed: -0.5
  jam_threshold: 0.15
  minimum_motor_output_to_prevent_jam: 0.25

global_elevator:
  enabled_button: ipb_operator_right_bumper
  increment_up_button: ipb_operator_y
  increment_down_button: ipb_operator_a
  initial_speed: 0.0
  elevator_increment: 0.1

global_turret:
  micro_axis: ipn_operator_right_y
  macro_axis: ipn_operator_right_x
  y_axis_scalar: 0.1
  aim_from_trench: 75.0

global_flywheel:
  micro_adjust_axis: ipn_operator_left_x
  macro_adjust_axis: ipn_operator_left_y
  initial_speed: 0.0
  y_axis_scalar: 1.0
  speed_profile:
    10.0: 6250
    15.0: 5500
    18.0: 5300
    24.0: 6000

global_climber:
  joystick: ipn_operator_left_y
  override_button: ipb_operator_dpad_right
  minimum_climber_position: 2.0
  maximum_climber_position: 70.0
  override_scale_factor: 0.2

log:
#  ips_selected_auto: true
#  ipb_robot_has_been_zeroed: true
#  ipb_drivetrain_safe_temperature: true
#  ipn_turret_position: true
#  ipn_flywheel_primary_velocity: true
#  ipb_turret_limelight_locked: true
#  ipb_turret_aligned: true
#  ipb_flywheel_primed: true
#  ipb_primed_to_shoot: true
#  ipb_endgame_enabled: true


global_webdashboard:

  auto_selector:
    origins: [right_8ball_trench, goal_8ball_generator, left_5ball_steal, anywhere_3ball_none]
    destinations: [none]
    actions: [none]

  match_values:

    ips_selected_auto:
      display_name: Auto
      type: auto

    ipb_robot_has_been_zeroed:
      display_name: Robot Zeroed
      type: boolean

    ipb_use_limelight_targeting:
      display_name: Use Limelight
      type: boolean

    ipb_use_navx_alignment:
      display_name: Use Navx
      type: boolean

    ipb_drivetrain_safe_temperature:
      display_name: Drivetrain Safe Temp
      type: boolean

    ipb_endgame_enabled:
      display_name: Climb Enabled
      type: boolean

    ipn_turret_position:
      display_name: Turret Position
      type: value

    ipn_flywheel_velocity_adjustment:
      display_name: Flywheel Velocity Adjustment
      type: value

    ipn_drivetrain_temperature:
      display_name: Drivetrain Temperature
      type: value

    ipn_flywheel_primary_temperature:
      display_name: Flywheel Temperature
      type: value

    logger:
      type: log
      display_name: Logger
      level: INFO

    ipb_turret_limelight_locked:
      display_name: Limelight
      type: other

    ipb_turret_aligned:
      display_name: Turret
      type: other

    ipb_flywheel_primed:
      display_name: Flywheel
      type: other

    ipb_primed_to_shoot:
      display_name: Primed
      type: other